//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.07 at 04:30:29 PM MSK 
//


package ru.gothmog.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.gothmog.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _HouseMr_QNAME = new QName("http://www.gothmog.ru/ws", "mr");
    private final static QName _HouseKadNom_QNAME = new QName("http://www.gothmog.ru/ws", "kad_nom");
    private final static QName _HouseAddress_QNAME = new QName("http://www.gothmog.ru/ws", "address");
    private final static QName _HouseAo_QNAME = new QName("http://www.gothmog.ru/ws", "ao");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.gothmog.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link House }
     * 
     */
    public House createHouse() {
        return new House();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gothmog.ru/ws", name = "mr", scope = House.class)
    public JAXBElement<String> createHouseMr(String value) {
        return new JAXBElement<String>(_HouseMr_QNAME, String.class, House.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gothmog.ru/ws", name = "kad_nom", scope = House.class)
    public JAXBElement<String> createHouseKadNom(String value) {
        return new JAXBElement<String>(_HouseKadNom_QNAME, String.class, House.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gothmog.ru/ws", name = "address", scope = House.class)
    public JAXBElement<String> createHouseAddress(String value) {
        return new JAXBElement<String>(_HouseAddress_QNAME, String.class, House.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.gothmog.ru/ws", name = "ao", scope = House.class)
    public JAXBElement<String> createHouseAo(String value) {
        return new JAXBElement<String>(_HouseAo_QNAME, String.class, House.class, value);
    }

}
